### ISSUE TITLE
meta descriptions not working

### ISSUE THREAD

**Issue by DaveSkender** [facioquo/uswds-design-patterns#6]
When trying to add HTML meta page descriptions, they do not showup.  Found in #5 
What we implemented:
- `meta` loaded in root module
- `meta` created and defined  as a service in page constructors

### Done when:

- [x] meta descriptions work
- [ ] sitemap.xml works for all routes
- [x] add URL in banner mention of GitHub repo
- [x] more meta icons
